all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    control_plane:
      hosts:
        cp-arm64:
          ansible_host: 192.168.10.10
          k8s_node_name: cp-arm64 # = hostname
    workers_public:
      hosts:
        wk-public-amd64:
          ansible_host: 192.168.10.11
          k8s_node_name: wk-public-amd64
    workers:
      hosts:
        wk-amd64:
          ansible_host: 192.168.10.12
          k8s_node_name: wk-amd64
